"""The JS look-through must give the SAME answer as the Python one.

WHY THIS FILE IS THE WHOLE ARGUMENT
    ``products/site/lookthrough.js`` is a second implementation of a
    calculation this repo already has in Python. Two implementations of one
    calculation is the most reliable way to end up with two answers to one
    question, and most of ``LESSONS.md`` is variations on that theme. The
    static page is only defensible if the agreement is *proven on every
    build* rather than believed.

    So this file drives the JS under node over fixtures generated BY the
    Python, and requires exact agreement:

    * ``test_index_phrase_parity`` / ``test_classify_parity`` — every scheme
      name in the live AMFI master (3,400+ distinct names), plus the ticker
      tables and the paste shapes a user actually types. ``index_phrase`` is
      a lossy reduction tuned over real Indian scheme names; a port that
      agrees on twenty hand-picked examples proves nothing, and one that
      agrees on three thousand is a port.
    * ``test_golden_book_parity`` — whole books through the real engine, with
      every weight compared at 1e-12. This is the arithmetic the headline is
      made of.

    A failure here means the page is showing a different number from the
    server and must not ship. It is not a flaky-test problem to route around.

WHAT IS DELIBERATELY *NOT* ASSERTED
    The JS resolver is NARROWER than Python's: the server also consults
    AMFI's scheme master by ISIN and by exact name (14,000 schemes, far too
    large to send to a browser), which gives it AMFI's own SEBI category.
    The JS resolves on the typed text alone.

    That difference is one-directional and the tests pin the direction: the
    JS may REFUSE a fund Python would have unpacked, and must never unpack
    one Python refused, nor unpack it into a different index. A refusal the
    reader can see is recoverable; a wrong unpack reports success while
    being wrong, which is the failure this product cannot survive.
    ``test_js_never_unpacks_what_python_refused`` is that check.

REGENERATING
    PYTHONPATH=. .venv/bin/python scripts/export_lookthrough_data.py

    The fixture and the page data carry the same ``generated`` date;
    ``test_fixture_matches_the_shipped_data`` fails if they drift, because a
    stale fixture would validate a page built from different numbers.
"""

from __future__ import annotations

import gzip
import json
import shutil
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
PAGE_DATA = REPO / "products/site/data/lookthrough.json"
FIXTURE = REPO / "tests/fixtures/lookthrough_parity.json.gz"
JS = REPO / "products/site/lookthrough.js"

#: Weights are compared at this tolerance. It is tight on purpose: a looser
#: one would hide the slow drift this file exists to catch, and both sides are
#: IEEE doubles doing the same multiplications, so they have no excuse to
#: differ at all.
TOL = 1e-12

pytestmark = pytest.mark.skipif(
    shutil.which("node") is None,
    reason="node is not installed, so the JS cannot be executed to compare it",
)


def _require_artifacts() -> None:
    missing = [p for p in (PAGE_DATA, FIXTURE, JS) if not p.is_file()]
    if missing:
        pytest.fail(
            "missing "
            + ", ".join(str(p.relative_to(REPO)) for p in missing)
            + " — run: PYTHONPATH=. .venv/bin/python scripts/export_lookthrough_data.py"
        )


def _run_js(script: str) -> object:
    """Execute a node snippet with the engine loaded, return its JSON stdout."""
    _require_artifacts()
    prelude = f"""
const zlib = require("zlib");
const fs = require("fs");
const LT = require({json.dumps(str(JS))});
const data = require({json.dumps(str(PAGE_DATA))});
// The fixture ships gzipped; node inflates it rather than keeping a second
// uncompressed copy on disk that could drift from the compressed one.
const fixture = JSON.parse(zlib.gunzipSync(fs.readFileSync({json.dumps(str(FIXTURE))})).toString("utf8"));
const engine = new LT.Engine(data);
"""
    proc = subprocess.run(
        ["node", "-e", prelude + script],
        capture_output=True,
        text=True,
        timeout=180,
        cwd=str(REPO),
    )
    if proc.returncode != 0:
        pytest.fail(f"node exited {proc.returncode}\nSTDERR:\n{proc.stderr}\nSTDOUT:\n{proc.stdout[:2000]}")
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        pytest.fail(f"node did not emit JSON ({exc})\nSTDOUT:\n{proc.stdout[:2000]}\nSTDERR:\n{proc.stderr[:2000]}")


@pytest.fixture(scope="module")
def fixture_blob() -> dict:
    _require_artifacts()
    with gzip.open(FIXTURE, "rt", encoding="utf-8") as fh:
        return json.load(fh)


@pytest.fixture(scope="module")
def page_blob() -> dict:
    _require_artifacts()
    return json.loads(PAGE_DATA.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# The artifacts themselves
# ---------------------------------------------------------------------------


def test_fixture_matches_the_shipped_data(fixture_blob, page_blob):
    """A stale fixture would prove the JS agrees with numbers nobody ships."""
    assert fixture_blob["generated"] == page_blob["generated"], (
        "the parity fixture and the page data were generated on different days; "
        "re-run scripts/export_lookthrough_data.py so both come from one export"
    )


def test_page_data_carries_no_test_corpus(page_blob):
    """The 690 KB of test evidence must not be sent to every visitor."""
    assert "parity" not in page_blob
    assert "golden" not in page_blob
    assert PAGE_DATA.stat().st_size < 400_000, (
        f"page data is {PAGE_DATA.stat().st_size:,} bytes — something large leaked into it"
    )


def test_every_exported_index_sums_to_one(page_blob):
    """Every figure on the page is a share of this, so it cannot be 0.97."""
    for name, blob in page_blob["indices"].items():
        total = sum(blob["weights"].values())
        assert abs(total - 1.0) < 1e-9, f"{name} weights sum to {total!r}"


def test_an_excluded_constituent_is_recorded_not_silently_dropped(page_blob):
    """NIFTY 500 drops names Yahoo has no cap for; the reason must survive.

    The weights are renormalised over what is left, which is the honest
    handling — but only if the omission is stated. A reader comparing our
    497 against NSE's 501 deserves the reason, not a discrepancy.
    """
    for name, blob in page_blob["indices"].items():
        for entry in blob["excluded"]:
            assert len(entry) == 2 and entry[1].strip(), f"{name} excluded {entry[0]} without a reason"


# ---------------------------------------------------------------------------
# Parity on the text reduction — the part most likely to drift
# ---------------------------------------------------------------------------


def test_parity_corpus_is_actually_large(fixture_blob):
    """Guards the guard: a corpus of 12 rows would make the parity tests lie."""
    rows = fixture_blob["parity"]["rows"]
    assert len(rows) > 1000, (
        f"only {len(rows)} parity rows — the AMFI master probably failed to load "
        "during export, so the parity tests below are not testing much"
    )


def test_index_phrase_parity(fixture_blob):
    """Python's index_phrase and the JS port must agree on every row."""
    out = _run_js(
        """
const bad = [];
for (const row of fixture.parity.rows) {
  const got = engine.indexPhrase(row.text);
  if (got !== row.phrase) bad.push({text: row.text, py: row.phrase, js: got});
}
console.log(JSON.stringify({n: fixture.parity.rows.length, bad: bad.slice(0, 25), nbad: bad.length}));
"""
    )
    assert out["nbad"] == 0, (
        f"{out['nbad']} of {out['n']} names reduce differently in JS than in Python.\n"
        + "\n".join(f"  {b['text']!r}\n    python={b['py']!r}\n    js    ={b['js']!r}" for b in out["bad"])
    )


def test_classify_parity(fixture_blob):
    """index / active / unknown must agree on every row.

    Classification decides whether the reader is told "a manager picks these"
    or "this tracks an index we do not hold a list for". Those are different
    sentences about their money.
    """
    out = _run_js(
        """
const bad = [];
for (const row of fixture.parity.rows) {
  const got = engine.classify(row.text, row.category);
  if (got !== row.classification) bad.push({text: row.text, cat: row.category, py: row.classification, js: got});
}
console.log(JSON.stringify({n: fixture.parity.rows.length, bad: bad.slice(0, 25), nbad: bad.length}));
"""
    )
    assert out["nbad"] == 0, f"{out['nbad']} of {out['n']} names classify differently.\n" + "\n".join(
        f"  {b['text']!r} (cat={b['cat']!r}) python={b['py']!r} js={b['js']!r}" for b in out["bad"]
    )


# ---------------------------------------------------------------------------
# Parity on the arithmetic — the numbers the headline is made of
# ---------------------------------------------------------------------------


def test_golden_book_parity(fixture_blob):
    """Whole books, every weight, at 1e-12."""
    out = _run_js(
        """
const results = [];
for (const g of fixture.golden) {
  let r;
  try { r = engine.lookThrough(g.input); }
  catch (e) { r = {threw: String(e && e.message || e)}; }
  results.push({label: g.label, got: r});
}
console.log(JSON.stringify(results));
"""
    )
    by_label = {r["label"]: r["got"] for r in out}
    problems: list[str] = []

    for g in fixture_blob["golden"]:
        label, exp = g["label"], g["expect"]
        got = by_label.get(label)
        if got is None:
            problems.append(f"[{label}] JS produced no result")
            continue
        if got.get("threw"):
            problems.append(f"[{label}] JS threw: {got['threw']}")
            continue

        if bool(got.get("computed")) != bool(exp["computed"]):
            problems.append(
                f"[{label}] computed: python={exp['computed']} js={got.get('computed')} "
                f"(js reason: {got.get('not_computed_reason')!r})"
            )
            continue
        if not exp["computed"]:
            continue

        for key in ("n_listed", "n_unpacked", "n_companies"):
            if got.get(key) != exp[key]:
                problems.append(f"[{label}] {key}: python={exp[key]} js={got.get(key)}")

        py_lines = {ln["symbol"]: ln for ln in exp["lines"]}
        js_lines = {ln["symbol"]: ln for ln in got.get("rows", [])}

        only_py = sorted(set(py_lines) - set(js_lines))
        only_js = sorted(set(js_lines) - set(py_lines))
        if only_py:
            problems.append(f"[{label}] python has holdings JS does not: {only_py[:10]}")
        if only_js:
            problems.append(f"[{label}] JS invented holdings python does not have: {only_js[:10]}")

        for sym in sorted(set(py_lines) & set(js_lines)):
            p, j = py_lines[sym], js_lines[sym]
            if abs(float(p["actual"]) - float(j["actual"])) > TOL:
                problems.append(f"[{label}] {sym} actual: python={p['actual']!r} js={j['actual']!r}")
            pl, jl = p["listed"], j["listed"]
            if (pl is None) != (jl is None):
                problems.append(f"[{label}] {sym} listed presence: python={pl!r} js={jl!r}")
            elif pl is not None and abs(float(pl) - float(jl)) > TOL:
                problems.append(f"[{label}] {sym} listed: python={pl!r} js={jl!r}")
            if p["kind"] != j["kind"]:
                problems.append(f"[{label}] {sym} kind: python={p['kind']!r} js={j['kind']!r}")

    assert not problems, "the static page computes different numbers:\n" + "\n".join("  " + p for p in problems)


def test_js_never_unpacks_what_python_refused(fixture_blob):
    """The permitted divergence has ONE direction, and this is it.

    The JS has no AMFI master, so it may refuse a fund Python resolved. It
    must never do the opposite: unpacking a fund Python left alone, or
    unpacking it into a different index, puts companies in the reader's
    portfolio that are not there and reports success doing it.
    """
    out = _run_js(
        """
const results = [];
for (const g of fixture.golden) {
  let r;
  try { r = engine.lookThrough(g.input); } catch (e) { r = {funds: []}; }
  results.push({label: g.label, funds: r.funds || []});
}
console.log(JSON.stringify(results));
"""
    )
    by_label = {r["label"]: r["funds"] for r in out}
    problems: list[str] = []

    for g in fixture_blob["golden"]:
        if not g["expect"]["computed"]:
            continue
        py = {f["label"].upper(): f for f in g["expect"]["funds"]}
        js = {f["label"].upper(): f for f in by_label.get(g["label"], [])}
        for key, jf in js.items():
            pf = py.get(key)
            if pf is None:
                continue
            if jf["unpacked"] and not pf["unpacked"]:
                problems.append(
                    f"[{g['label']}] {key}: JS unpacked a fund python refused (JS index={jf.get('index')!r})"
                )
            if jf["unpacked"] and pf["unpacked"] and jf.get("index") != pf.get("index"):
                problems.append(
                    f"[{g['label']}] {key}: index disagreement python={pf.get('index')!r} js={jf.get('index')!r}"
                )

    assert not problems, "the static page over-claims:\n" + "\n".join("  " + p for p in problems)


# ---------------------------------------------------------------------------
# The refusals the page owes the reader
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "book, expect_in_reason",
    [
        ("HDFCBANK 100 units\nRELIANCE 50 units", "share counts"),
        ("HDFCBANK 1,20,000\nRELIANCE 50000", "Indian digit grouping"),
        ("HDFCBANK 2 crore\nRELIANCE 1 crore", "crore"),
        ("", "nothing was pasted"),
    ],
)
def test_shapes_the_page_refuses_rather_than_guesses(book, expect_in_reason):
    """Each of these has a plausible wrong reading, which is why it is refused.

    "1,20,000" is 120000 to an Indian reader and 1.2 to a naive parser;
    guessing produces a confidently wrong headline, so the page says what to
    change instead.
    """
    out = _run_js(
        f"""
let r;
try {{ r = engine.lookThrough({json.dumps(book)}); }}
catch (e) {{ r = {{computed: false, not_computed_reason: "threw: " + String(e && e.message || e)}}; }}
console.log(JSON.stringify(r));
"""
    )
    assert out["computed"] is False, f"expected a refusal for {book!r}, got a computed answer"
    reason = out.get("not_computed_reason") or ""
    assert expect_in_reason.lower() in reason.lower(), f"reason {reason!r} does not mention {expect_in_reason!r}"


def test_a_refusal_always_says_what_to_change():
    """A refusal with no instruction is a dead end the reader cannot leave."""
    out = _run_js(
        """
const books = [
  "HDFCBANK 100 units",
  "HDFCBANK 1,20,000",
  "HDFCBANK 2 lakh",
  "",
  "   \\n  \\n ",
  "no number here",
];
const out = [];
for (const b of books) {
  let r;
  try { r = engine.lookThrough(b); } catch (e) { r = {computed: false, not_computed_reason: ""}; }
  if (r.computed !== true) out.push({book: b, reason: r.not_computed_reason || ""});
}
console.log(JSON.stringify(out));
"""
    )
    for row in out:
        assert row["reason"].strip(), f"refused {row['book']!r} with an empty reason"


def test_no_advice_language_in_any_string_the_page_produces():
    """This product is an audit. Advice is regulated, and we do not give it."""
    from agent.portfolio import audit as A

    out = _run_js(
        """
const books = [
  "HDFCBANK 12%\\nNIFTYBEES 40%\\nGOLDBEES 18%\\nParag Parikh Flexi Cap Fund 30%",
  "HDFCBANK 100 units",
  "NIFTYBEES 100%",
  "",
];
const strings = [];
function walk(o) {
  if (typeof o === "string") strings.push(o);
  else if (Array.isArray(o)) o.forEach(walk);
  else if (o && typeof o === "object") Object.keys(o).forEach(k => walk(o[k]));
}
for (const b of books) {
  let r;
  try { r = engine.lookThrough(b); } catch (e) { r = {}; }
  walk(r);
}
console.log(JSON.stringify(strings));
"""
    )
    offenders = [(s, A.advice_words_in(s)) for s in out if A.advice_words_in(s)]
    assert not offenders, "advice language on the static page:\n" + "\n".join(
        f"  {words!r} in {s!r}" for s, words in offenders
    )
